### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by camilleldn** [camilleldn/boxen#51]
## Checklist for building a new machine

- [x] Copy this checklist to a new GitHub issue
- [x] Transfer Documents, Dropbox and Pictures to disk;
- [x] TimeMachine backup
- [x] Restart with cmd+R
- [x] Disk Utility: erase disk
- [x] Resintall MacOsX
- [x] Install XCode
- [x] `sudo gcc`
- [x] run
  ```
  sudo mkdir -p /opt/boxen
  
  sudo chown ${USER}:staff /opt/boxen
  
  git clone <location of my new git repository> /opt/boxen/repo
  
  cd /opt/boxen/repo
  
  ./script/boxen
  ```
- [x] boxen
  - [x] rerun until no more errors... (the apps from the App Store along, the puppet code for the app store is flaky at times)
  - [x] before the run do `sudo ls` if some tty errors occur
  - [x] if some permissions errors occur: `sudo chown -R "$USER":admin /usr/local`
- [x] `brew linkapps; find ~/Applications -type l | while read f; do osascript -e "tell app \"Finder\" to make new alias file at POSIX file \"/Applications\" to POSIX file \"$(stat -f%Y "$f")\""; rm "$f"; done`
- [x] Start some applications (some may need accessibility settings)
  - [x] Caffeine
  - [x] Cheatsheet
  - [x] ColorSnapper
  - [x] Day 0
  - [x] Day One
  - [x] Duet
  - [x] MacFamilyTree 7 
  - [x] Messages
  - [x] Moom
  - [x] NoSleep
  - [x] Plex Home Theatre
  - [x] PopClip
  - [x] Satellite Eyes
  - [x] Scratch
  - [x] The Unarchiver
- [x] Start browsers: sign in, sign to LastPass, sign in to Pocket
  - [x] Firefox
  - [x] Google Chrome
  - [x] Opera
- [x] Start and log into applications
  - [x] Airmail
  - [x] Amazon Cloud Drive
  - [x] Dropbox
  - [x] Evernote
  - [x] Flux
  - [x] Google Drive
  - [x] iTunes
  - [x] Kindle
  - [x] Paprika Recipe Manager
  - [x] Pocket
  - [x] Quickcast
  - [x] Rescuetime
  - [x] Screenhero
  - [x] Skype
  - [x] Slack: lm-tools, ukgovernmentdigital, ruby-london, gds-alumni, rubytogether-members, ukgovcamp, pullrequestday
  - [x] Spotify
  - [x] Steam
  - [x] TweetDeck
  - [x] Wunderlist
- [x] Start and enter license details
  - [x] Alfred
  - [x] Clean My Mac
  - [x] Omnigraffle
  - [x] Screenflow
  - [x] Sketch
  - [x] Sublime
- [x] ScreenSaver Ninja
  - [x] Import from Dropbox
  - [x] Start and enter license details
  - [x] Setup dashboards
- [x] Delicious Library (only RedQueen)
  - [x] Import library from dropbox XML
- [x] Sourcetree
  - [x] Import Code folder
- [x] Infinit
  - [x] Import from Dropbox
  - [x] Sign in
- [x] Skitch
  - [x] Sign in to Evernote
- [x] Sonos
  - [x] Setup with house network
- [x] XCode
  - [x] Open, install simulator and documentation
- [x] Dash
  - [x] Activate full version
  - [x] Download docsets
- [x] Cura
  - [x] Install from Dropbox
- [x] Private Internet Access
  - [x] Install from Dropbox
- [x] Bartender
  - [x] Configure
- [x] Reeder
  - [x] log in to Feedly with Google account
- [x] Photos
  - [x] Open once copy of old photo library in place
  - [x] Setup iCloud
  - [x] Setup extensions
- [x] Adobe Creative Cloud
  - [x] `open /opt/homebrew-cask/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app`
- [x] Hemingway
  - [x] copy out of Dropbox
- [x] YNAB
  - [x] copy out of Dropbox
- [x] Atom
  - [x] Install command line utility
- [x] `keybase login`
- [x] Plugin for printer
- [x] Genereate new set of ssh keys: move to GitHub and Heroku
- [x] Use zsh
  - [x] add /opt/boxen/homebrew/bin/zsh to /etc/shells
  - [x] chsh -s /opt/boxen/homebrew/bin/zsh
- [x] Run `dot` without errors
- [x] Trello workflow
  - [x] [download](http://www.packal.org/workflow/trello-alfred)
  - [x] open workflow folder, copy setup from setup-config
- [x] Postgres:
  ```
   brew install postgresql
   
   initdb /usr/local/var/postgres
   
   cp /usr/local/Cellar/postgresql/9.2.4/org.postgresql.postgres.plist ~/Library/LaunchAgents/
   
   launchctl load -w ~/Library/LaunchAgents/org.postgresql.postgres.plist
   ```
- [x] `vim +PluginInstall +qall`
- [x] `mkdir ~/.gnupg` and `keybase login`
- [x] Add `Code` and `Pictures` to finder favourites
- [x] Setup SMS forwarding
- [x] Check accessibility settings
- [x] TimeMachine backup

**Comment by camilleldn** [comment]
<location of>.. -> https://github.com/camilleldn/boxen.git

**Comment by camilleldn** [comment]
attempt with docs,and photos test sync

**Comment by camilleldn** [comment]
remove personal access token pre: first run

**Comment by camilleldn** [comment]
gif-brewery-3-video-to-gif/id1081413713?mt=12 ???

**Comment by camilleldn** [comment]
remove sourcetree

**Comment by camilleldn** [comment]
https://itunes.apple.com/gb/app/xcode/id497799835?mt=12

**Comment by camilleldn** [comment]
https://itunes.apple.com/gb/app/screensaver-ninja/id1057884151?mt=12
